# Use an official node.js runtime as a parent image
FROM node:22-alpine

#Set the working directory in the container
WORKDIR /app

#Copy the package.json and the package-lock.json files to the container
COPY package*.json .

# install dependencies
RUN npm install

# copy the rest of the application code (docker builds images from the top down, so whenever we change the src code, only this line is executed,
#everything on top wont be touched which is good)
COPY . .

#Expose the port that the app runs on
EXPOSE 5003

#Define the command to run your application
CMD ["node", "./src/server.js"]